### ISSUE TITLE
[BUG] streams not shown on windows

### ISSUE THREAD

**Issue by r-hannuschka** [q-masters/vsqlik#502]
as described in #281 streams are not visible on windows machine.

**Comment by r-hannuschka** [comment]
@davidwales @konne 

For testing added the new version which can imported to vscode.

[vscode-qlik-1.0.1.vsix.zip](https://github.com/q-masters/vsqlik/files/5182696/vscode-qlik-1.0.1.vsix.zip)

**Comment by r-hannuschka** [comment]
thx @konne for creating the pre release

https://github.com/q-masters/vsqlik/releases/tag/1.0.1-beta

**Comment by davidwales** [comment]
@konne @r-hannuschka The pre-release works!

**Comment by davidwales** [comment]
However, I got the following error message from the VSIX installer (it didn't stop the extension from working):

```
8/09/2020 8:37:56 AM - Microsoft VSIX Installer
8/09/2020 8:37:56 AM - -------------------------------------------
8/09/2020 8:37:56 AM - vsixinstaller.exe version:
8/09/2020 8:37:56 AM - 16.5.2047
8/09/2020 8:37:56 AM - -------------------------------------------
8/09/2020 8:37:56 AM - Command line parameters:
8/09/2020 8:37:56 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\dwales\AppData\Local\Temp\vscode-qlik-1.1.0-tags-1-0-1-beta.1.vsix
8/09/2020 8:37:56 AM - -------------------------------------------
8/09/2020 8:37:56 AM - Microsoft VSIX Installer
8/09/2020 8:37:56 AM - -------------------------------------------
8/09/2020 8:37:58 AM - Initializing Install...
8/09/2020 8:37:58 AM - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__67_1(String s)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by r-hannuschka** [comment]
Wow never see this before, but i never used a pre-release. I start this one in debugging mode (requires all the node-modules) or simply create my own vsix file (also requires all node modules).

Possible he becomes trouble because in the package.json is version 1.0.1 and this one is called 1.1.0-tags-1-0-1-beta.1, he might check file name and package.json version number. But this is only the vsix installer to install a vsix file it seems nothing about the extension manager.

Anyway glad is working and thx alot for the issues you send us which helps us to improve the extension.
